[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff.config.settings]
args = ["--ignore", "E501", "--select", "I001"]

[language.formatter]
command = "ruff"
args = ["format", "-"]

[language-server.ruff]
command = "ruff"
args = ["server"]
